### ISSUE TITLE
Setting the origin

### ISSUE THREAD

**Issue by SteveGoldstein** [skent259/covid-19#2]
Nice!  Thank you Sean.

Suggestions for one more visualization:   Make the x-axis # of days since N cases (N=10 or 20).  This plot is from Mikhail Kats in engineering:

 
![WI_counties_march23_assembled](https://user-images.githubusercontent.com/7879996/77366771-bb7df380-6d26-11ea-9711-c270773623d1.png)

**Comment by klittle314** [comment]
Hi Sean, I have code built for another project that makes small multiples via ggplot2--all wisconsin counties could be displayed on one display.   Rates seem important, Milwaukee and Dane not only have more cases but more people.   Will invite you to one of my shiny projects so you can see a couple of options for plotting data from multiple parallel systems (clinics in my example, counties in yours)..

**Comment by skent259** [comment]
@SteveGoldstein, thanks for your input.  In #3 I've added a drop-down menu under the county plot that allows you to choose between "Date" (default) and "Days since 10 cases".  I think that should address your point!

@klittle314, I see what you mean and I think that could certainly be useful.  It actually gave me a few ideas that I'll check out today.  I'm thinking something along the lines of https://hafen.github.io/geofacet/ might be cool, or something like the second chart (after the map) here: https://www.nytimes.com/interactive/2020/world/coronavirus-maps.html.

**Comment by klittle314** [comment]
split to new enhancement issue.

**Comment by skent259** [comment]
Great.  Closing this issue unless @SteveGoldstein has other thoughts.
